import Foundation

@main
struct MovieQuizTests {
    static func main() throws {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let media = try decoder.decode(MovieQuizMedia.self, from: Data(#"{"id":597,"images":{"backdrops":[{"file_path":"/title.jpg","iso_639_1":"en","vote_average":10},{"file_path":"/scene.jpg","iso_639_1":null,"vote_average":7}]}}"#.utf8))
        precondition(media.textlessBackdropPath == "/scene.jpg", "Avoid images tagged with title text")
        let answer = MovieQuizChoice(id: 597, title: "Titanic")
        let candidates = [answer, .init(id: 1, title: " TITANIC! "), .init(id: 603, title: "The Matrix"), .init(id: 603, title: "Matrix"), .init(id: 329, title: "Jurassic Park"), .init(id: 27205, title: "Inception")]
        let choices = MovieQuizRound.choices(answer: answer, candidates: candidates, seed: "2026-09-30")
        precondition(choices.count == 4 && Set(choices.map(\.id)).count == 4)
        precondition(choices.filter { $0.id == answer.id }.count == 1)
        precondition(choices == MovieQuizRound.choices(answer: answer, candidates: candidates, seed: "2026-09-30"))
        precondition(MovieQuizRound.choices(answer: answer, candidates: [], seed: "x").isEmpty, "Never display an incomplete choice set")
        let round = MovieQuizRound(answerID: answer.id, choices: choices, backdropPath: nil, posterPath: nil)
        var state = MovieQuizState(round: round)
        precondition(!state.choose(99999) && state.attempts == 0)
        precondition(state.choose(603) && state.attempts == 1 && state.hintRevealed)
        precondition(!state.choose(603) && state.attempts == 1, "Repeated taps cannot consume attempts")
        precondition(state.choose(597) && state.isSolved && state.points == 2)
        precondition(!state.choose(329) && state.attempts == 2)
        let restored = try JSONDecoder().decode(MovieQuizState.self, from: JSONEncoder().encode(state))
        precondition(restored == state, "Persist eliminated choices and assisted score")
        var perfect = MovieQuizState(round: round)
        _ = perfect.choose(597)
        precondition(perfect.points == 3)
        var assisted = MovieQuizState(round: round)
        assisted.revealHint()
        _ = assisted.choose(597)
        precondition(assisted.points == 2)
        var skipped = MovieQuizState(round: round)
        skipped.skip()
        precondition(skipped.isFinished && !skipped.isSolved && skipped.points == 0)
        precondition(!skipped.choose(597))
        for revealCount in 0...2 {
            var zoom = MovieQuizState(round: round)
            zoom.enableZoomReveal()
            precondition(zoom.zoomStep == 0 && zoom.zoomScale == 3 && zoom.revealedTiles == nil)
            for _ in 0..<revealCount { precondition(zoom.zoomOut()) }
            precondition(zoom.availablePoints == 3 - revealCount)
            precondition(zoom.zoomScale == [3.0, 1.8, 1.0][revealCount])
            let restoredZoom = try JSONDecoder().decode(MovieQuizState.self, from: JSONEncoder().encode(zoom))
            precondition(restoredZoom == zoom)
            zoom.enableTileReveal()
            zoom.enableZoomReveal()
            precondition(zoom.zoomStep == revealCount && zoom.revealedTiles == nil, "Reveal modes cannot reset or switch during play")
            precondition(zoom.choose(597) && zoom.points == 3 - revealCount)
            precondition(!zoom.zoomOut(), "Solved zoom rounds cannot change earned points")
        }
        var fullyZoomed = MovieQuizState(round: round)
        fullyZoomed.enableZoomReveal()
        precondition(fullyZoomed.zoomOut() && fullyZoomed.zoomOut() && !fullyZoomed.zoomOut())
        fullyZoomed.revealHint()
        for choice in choices where choice.id != answer.id { _ = fullyZoomed.choose(choice.id) }
        precondition(fullyZoomed.choose(597) && fullyZoomed.points == 1)
        var skippedZoom = MovieQuizState(round: round)
        skippedZoom.enableZoomReveal()
        skippedZoom.skip()
        precondition(!skippedZoom.zoomOut() && skippedZoom.zoomStep == 0 && skippedZoom.points == 0)
        var unavailableZoom = MovieQuizState(round: round)
        unavailableZoom.enableZoomReveal()
        _ = unavailableZoom.zoomOut()
        unavailableZoom.disableTileRevealForUnavailableImage()
        unavailableZoom.enableZoomReveal()
        precondition(unavailableZoom.zoomStep == nil && unavailableZoom.zoomScale == 1 && !unavailableZoom.zoomOut())
        precondition(unavailableZoom.availablePoints == 3 && unavailableZoom.hintRevealed)
        var tiles = MovieQuizState(round: round)
        tiles.enableTileReveal()
        tiles.enableZoomReveal()
        precondition(tiles.zoomStep == nil, "Existing tile mode stays intact")
        precondition(tiles.visibleTileIndices == [4] && tiles.availablePoints == 3)
        precondition(!tiles.revealTile(-1) && !tiles.revealTile(9) && !tiles.revealTile(4))
        precondition(tiles.revealTile(0) && tiles.revealTile(1) && tiles.availablePoints == 3)
        precondition(tiles.revealTile(2) && tiles.availablePoints == 2)
        let restoredTiles = try JSONDecoder().decode(MovieQuizState.self, from: JSONEncoder().encode(tiles))
        precondition(restoredTiles == tiles)
        for tile in [3, 5] { _ = tiles.revealTile(tile) }
        precondition(tiles.availablePoints == 2)
        _ = tiles.revealTile(6)
        precondition(tiles.availablePoints == 1)
        for tile in [7, 8] { _ = tiles.revealTile(tile) }
        tiles.revealHint()
        _ = tiles.choose(603)
        precondition(tiles.availablePoints == 1)
        _ = tiles.choose(597)
        precondition(tiles.points == 1 && !tiles.revealTile(8))
        tiles.disableTileRevealForUnavailableImage()
        precondition(tiles.points == 1, "Image changes cannot mutate earned points")
        var fallback = MovieQuizState(round: round)
        fallback.enableTileReveal()
        fallback.disableTileRevealForUnavailableImage()
        precondition(fallback.visibleTileIndices.count == 9 && fallback.hintRevealed && !fallback.requestedHint)
        precondition(fallback.availablePoints == 3)
        _ = fallback.choose(597)
        precondition(fallback.points == 3)
        var difficultFallback = MovieQuizState(round: round)
        difficultFallback.enableTileReveal()
        difficultFallback.disableTileRevealForUnavailableImage()
        for choice in choices where choice.id != answer.id { _ = difficultFallback.choose(choice.id) }
        _ = difficultFallback.choose(answer.id)
        precondition(difficultFallback.points == 1, "Recovering from all wrong choices still earns a point without an image")
        var legacyMisses = MovieQuizState(round: round)
        for choice in choices where choice.id != answer.id { _ = legacyMisses.choose(choice.id) }
        _ = legacyMisses.choose(answer.id)
        precondition(legacyMisses.points == 0, "Existing untiled scores remain unchanged")
        var oldObject = try JSONSerialization.jsonObject(with: JSONEncoder().encode(perfect)) as! [String: Any]
        oldObject.removeValue(forKey: "revealedTiles")
        oldObject.removeValue(forKey: "imageUnavailable")
        oldObject.removeValue(forKey: "zoomStep")
        let legacy = try JSONDecoder().decode(MovieQuizState.self, from: JSONSerialization.data(withJSONObject: oldObject))
        precondition(legacy.revealedTiles == nil && legacy.visibleTileIndices.count == 9 && legacy.points == 3)
        precondition(legacy.zoomStep == nil && legacy.zoomScale == 1)
        var terminal = skipped
        terminal.enableTileReveal()
        terminal.enableZoomReveal()
        precondition(terminal.zoomStep == nil && !terminal.zoomOut())
        precondition(terminal.revealedTiles == nil && !terminal.revealTile(0))
        let defaults = UserDefaults(suiteName: "movie-quiz-tests")!
        defaults.removePersistentDomain(forName: "movie-quiz-tests")
        defer { defaults.removePersistentDomain(forName: "movie-quiz-tests") }
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "America/New_York")!
        let streak = MovieQuizParticipationStore(defaults: defaults, calendar: calendar)
        let day = ISO8601DateFormatter().date(from: "2026-09-30T18:00:00Z")!
        precondition(streak.recordCompletedRun(at: day) == 1)
        precondition(streak.recordCompletedRun(at: day) == 1)
        precondition(streak.recordCompletedRun(at: calendar.date(byAdding: .day, value: 1, to: day)!) == 2)
        precondition(streak.recordCompletedRun(at: calendar.date(byAdding: .day, value: 3, to: day)!) == 1)
        print("PASS: choices, answer guards, tile and zoom reveal penalties, persistence, legacy scores, free image fallback, streaks")
    }
}
